"""
OpenAPI examples for all API endpoints.

This module provides comprehensive, realistic examples for the FastAPI
OpenAPI documentation. Each router has its own examples module.

Usage:
    from app.openapi_examples.auth_examples import REGISTER_REQUEST_EXAMPLES, REGISTER_RESPONSES

    @router.post("/register", responses=REGISTER_RESPONSES)
    async def register(
        body: Annotated[StaffRegisterRequest, Body(openapi_examples=REGISTER_REQUEST_EXAMPLES)],
    ): ...
"""

# Auth examples
from app.openapi_examples.auth_examples import (
    REGISTER_REQUEST_EXAMPLES,
    REGISTER_RESPONSES,
    TOKEN_RESPONSES,
    USERINFO_RESPONSES,
)

# Events examples
from app.openapi_examples.events_examples import (
    LIST_ALL_EVENTS_RESPONSES,
    LIST_GUEST_EVENTS_RESPONSES,
    LIST_MEETUP_EVENTS_RESPONSES,
    LIST_STAFF_EVENTS_RESPONSES,
)

# Guests examples
from app.openapi_examples.guests_examples import (
    CREATE_MANUAL_GUEST_REQUEST_EXAMPLES,
    CREATE_MANUAL_GUEST_RESPONSES,
    CREATE_MAZMO_GUEST_REQUEST_EXAMPLES,
    CREATE_MAZMO_GUEST_RESPONSES,
    GET_GUEST_BY_MAZMO_HANDLE_RESPONSES,
    GET_GUEST_RESPONSES,
    LINK_MAZMO_REQUEST_EXAMPLES,
    LINK_MAZMO_RESPONSES,
    LIST_GUESTS_RESPONSES,
    UNLINK_MAZMO_RESPONSES,
    UPDATE_GUEST_REQUEST_EXAMPLES,
    UPDATE_GUEST_RESPONSES,
)

# Meetups examples
from app.openapi_examples.meetups_examples import (
    ADD_WALKIN_RESPONSES,
    CHECKIN_RESPONSES,
    CREATE_MEETUP_REQUEST_EXAMPLES,
    CREATE_MEETUP_RESPONSES,
    FINALIZE_MEETUP_RESPONSES,
    GET_MEETUP_RESPONSES,
    LIST_MEETUP_GUESTS_RESPONSES,
    LIST_MEETUPS_RESPONSES,
    SYNC_MEETUP_RESPONSES,
    UNDO_CHECKIN_REQUEST_EXAMPLES,
    UNDO_CHECKIN_RESPONSES,
    UNFINALIZE_MEETUP_RESPONSES,
)

# Organizations examples
from app.openapi_examples.organizations_examples import (
    ADD_MEMBER_REQUEST_EXAMPLES,
    ADD_MEMBER_RESPONSES,
    BAN_GUEST_REQUEST_EXAMPLES,
    BAN_GUEST_RESPONSES,
    CREATE_ORG_REQUEST_EXAMPLES,
    CREATE_ORG_RESPONSES,
    GET_ORG_RESPONSES,
    LIST_BANNED_IN_ORG_RESPONSES,
    LIST_ORG_MEMBERS_RESPONSES,
    LIST_ORGS_RESPONSES,
    REMOVE_MEMBER_RESPONSES,
    UNBAN_GUEST_RESPONSES,
    UPDATE_MEMBER_ROLE_REQUEST_EXAMPLES,
    UPDATE_MEMBER_ROLE_RESPONSES,
)

# Staff examples
from app.openapi_examples.staff_examples import (
    APPROVE_REQUEST_EXAMPLES,
    APPROVE_RESPONSES,
    DISABLE_REQUEST_EXAMPLES,
    DISABLE_RESPONSES,
    ENABLE_RESPONSES,
    LIST_PENDING_RESPONSES,
    LIST_STAFF_RESPONSES,
    ROLE_REQUEST_EXAMPLES,
    ROLE_RESPONSES,
)

__all__ = [
    # Organizations
    "ADD_MEMBER_REQUEST_EXAMPLES",
    "ADD_MEMBER_RESPONSES",
    # Meetups
    "ADD_WALKIN_RESPONSES",
    # Staff
    "APPROVE_REQUEST_EXAMPLES",
    "APPROVE_RESPONSES",
    "BAN_GUEST_REQUEST_EXAMPLES",
    "BAN_GUEST_RESPONSES",
    "CHECKIN_RESPONSES",
    # Guests
    "CREATE_MANUAL_GUEST_REQUEST_EXAMPLES",
    "CREATE_MANUAL_GUEST_RESPONSES",
    "CREATE_MAZMO_GUEST_REQUEST_EXAMPLES",
    "CREATE_MAZMO_GUEST_RESPONSES",
    "CREATE_MEETUP_REQUEST_EXAMPLES",
    "CREATE_MEETUP_RESPONSES",
    "CREATE_ORG_REQUEST_EXAMPLES",
    "CREATE_ORG_RESPONSES",
    "DISABLE_REQUEST_EXAMPLES",
    "DISABLE_RESPONSES",
    "ENABLE_RESPONSES",
    "FINALIZE_MEETUP_RESPONSES",
    "GET_GUEST_BY_MAZMO_HANDLE_RESPONSES",
    "GET_GUEST_RESPONSES",
    "GET_MEETUP_RESPONSES",
    "GET_ORG_RESPONSES",
    "LINK_MAZMO_REQUEST_EXAMPLES",
    "LINK_MAZMO_RESPONSES",
    # Events
    "LIST_ALL_EVENTS_RESPONSES",
    "LIST_BANNED_IN_ORG_RESPONSES",
    "LIST_GUESTS_RESPONSES",
    "LIST_GUEST_EVENTS_RESPONSES",
    "LIST_MEETUPS_RESPONSES",
    "LIST_MEETUP_EVENTS_RESPONSES",
    "LIST_MEETUP_GUESTS_RESPONSES",
    "LIST_ORGS_RESPONSES",
    "LIST_ORG_MEMBERS_RESPONSES",
    "LIST_PENDING_RESPONSES",
    "LIST_STAFF_EVENTS_RESPONSES",
    "LIST_STAFF_RESPONSES",
    # Auth
    "REGISTER_REQUEST_EXAMPLES",
    "REGISTER_RESPONSES",
    "REMOVE_MEMBER_RESPONSES",
    "ROLE_REQUEST_EXAMPLES",
    "ROLE_RESPONSES",
    "SYNC_MEETUP_RESPONSES",
    "TOKEN_RESPONSES",
    "UNBAN_GUEST_RESPONSES",
    "UNDO_CHECKIN_REQUEST_EXAMPLES",
    "UNDO_CHECKIN_RESPONSES",
    "UNFINALIZE_MEETUP_RESPONSES",
    "UNLINK_MAZMO_RESPONSES",
    "UPDATE_GUEST_REQUEST_EXAMPLES",
    "UPDATE_GUEST_RESPONSES",
    "UPDATE_MEMBER_ROLE_REQUEST_EXAMPLES",
    "UPDATE_MEMBER_ROLE_RESPONSES",
    "USERINFO_RESPONSES",
]
